### ISSUE TITLE
Blog Modern & Portfolio: header.php isn't using component files

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#100]
This becomes more obvious when you download the generated themes, but compare for example:

https://github.com/Automattic/theme-pattern-library/blob/master/types/portfolio/header.php to https://github.com/Automattic/theme-pattern-library/blob/master/types/business/header.php

For the portfolio and blog-modern types, although `branding/branding.php`, `site-logo/site-logo.php`, and `top-navigation/top-navigation.php` appear in the `components` directory, these files aren't actually used or called from anywhere. This leads to some confusion (and duplicated code!) when trying to figure out how all the pieces fit together.

**Comment by karmatosed** [comment]
I would possibly say this is a generation thing (totally may not be). We should only include in the zip the files that are being used - I agree there.

**Comment by davidakennedy** [comment]
I believe we've addressed this in a recent merge with lots of changes. See: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

If that's not the case, feel free to reopen or create a new issue, but I'm going to close for now since this references a much older file structure.
