### ISSUE TITLE
Primary menu is named inconsistently

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#148]
I generated a new classic-blog theme, but when I try to add items to my main menu, I just keep seeing the default WordPress page nav fallback. :(

This is because `register_nav_menus` registers the menu with an ID of `top`, whereas `header.php` is looking for a `primary` menu.

I actually experienced this with Pique many moons ago, so this time, it only tripped me up for about an hour. ;) I thought I'd fixed it then, but it looks like that's not the case—I'm seeing this for all blog types.

**Comment by laurelfulford** [comment]
After merging the fix for portfolio, I realized there's some inconsistencies in these files across themes (the issue addressed in unmerged #103). In some, the PR would fix; in others it would break the menu, or (for Modern blog) introduce a third menu ID. 

I think we should get the files consistent, and decide on a consistent ID for the menus before proceeding. Details below:

**Portfolio:**
* In header.php, the menu ID is 'primary'
* In functions.php, the ID is 'primary' (with the merged fix from #149)
* In components/top-navigation/top-navigation.php, the ID is 'top'. File is unused.

I think we should update this type to use the top-navigation.php, and roll back my merge.

**Modern:**
* In header.php, the menu ID is 'main'
* In functions.php, ID is 'top' (without merging #152)
* In components/top-navigation/top-navigation.php, the ID is 'top'. File is unused.

I think we should update this type to use the top-navigation.php instead.

**Classic:**
* In header.php, the menu ID is 'primary'
* In functions.php, ID is 'top' (without merging #153)
* In components/top-navigation/top-navigation.php, the ID is 'top'. File is unused.

I think we should update this type to use the top-navigation.php instead.

**Magazine:**
* No menu set in header.php - pulls in top-navigation.php instead
* In functions.php, ID is 'top' (without merging #150)
* In components/top-navigation/top-navigation.php, the ID is 'top'

Menu should be fine as is.

**Business:**
* No menu set in header.php - pulls in top-navigation.php instead
* In functions.php, ID is 'top' (without merging #151)
* In components/top-navigation/top-navigation.php, the ID is 'top'

Menu should be fine as is.

**In master branch:**
* No menu set in header.php - pulls in top-navigation.php instead
* In functions.php, ID is 'top' (without merging #154)
* In components/top-navigation/top-navigation.php, the ID is 'top'

Menu should be fine as is.

**Comment by laurelfulford** [comment]
I like to complicate things :persevere:  

A quicker fix that doesn't involve mucking around too much would be to revert #149 and just change the IDs in the header.php files to 'top'.

We could still tackle making the files consistent in #103, but have this resolved sooner.

**Comment by sarahmonster** [comment]
I thought about going with 'top' instead, but it seemed less useful—`top` is less descriptive/more prescriptive in terms of spatial arrangement. `Primary` indicates usage rather than layout—someone might choose to have their primary navigation anchored to the left-hand side of the window, but it's still the primary menu. 

I knew I'd fixed this issue before! :cry:  #103 is out-of-date now—I did it before we split the types into branches—and would need to be re-done. I can look into replicating this later today—it feels like the sanest option, and would make for cleaner files all-round.

**Comment by alaczek** [comment]
Agree that `primary` is more useful.

**Comment by laurelfulford** [comment]
I totally agree with the reasoning for using 'primary' - 'top' just required less edits :wink: 

We should probably also rename the /components/top-navigation/top-navigation.php file for consistency.

**Comment by sarahmonster** [comment]
This will need more work once we can work on branches—I'm re-opening for now since there are still issues that need cleaning up.

**Comment by karmatosed** [comment]
I actually would vote to keep top. It makes more semantic sense.

**Comment by karmatosed** [comment]
A future thing to consider could be iterating on how we have navigation. For example:
- navigation
- navigation/top-navigation
- navigation/anotherposition-navigation

That would reduce the number of component folders and could be a good approach.

**Comment by karmatosed** [comment]
Fixing as for now (until we have a united approach) using top.
