### ISSUE TITLE
Magazine: layout not as expected

### ISSUE THREAD

**Issue by karmatosed** [Automattic/theme-components#269]
The same here as Business and Blog Classic. On download, the layouts aren't as you'd expect with formatting.

**Comment by sixhours** [comment]
Related: #273

**Comment by davidakennedy** [comment]
@karmatosed What's wrong with the layout specifically? That way, I can fix. Thanks!

**Comment by davidakennedy** [comment]
I'm going to close this one out since I can't figure out what's not as expected. However, we can always reopen if more info is added and a fix is needed.

One note that may not be apparent is that the Sass files need to be compiled once a theme is downloaded. Otherwise, it certainly won't look as expected.

That will be included in the docs. 😄
